apiVersion: v1
kind: ConfigMap
metadata:
  name: mysite-config
data:
  default.conf: |
    server {
      listen                  81;
      server_name             _;
      location / {
       proxy_pass http://cvat-ui:80;
       }

       location /api/ {
        proxy_pass http://cvat:8080;
        client_max_body_size 2000M;
       }
      location /analytics/ {
      proxy_pass http://kibana:5601/;
      } 
 
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
    traefik.enable: "true"
    traefik.http.routers.cvat-ui.entrypoints: web
    traefik.http.routers.cvat-ui.rule: Host(`localhost`)
    traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-proxy
  name: cvat-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-proxy
  template:
    metadata:
      annotations:
        traefik.enable: "true"
        traefik.http.routers.cvat-ui.entrypoints: web
        traefik.http.routers.cvat-ui.rule: Host(`localhost`)
        traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
      labels:
        io.kompose.network/cvat: "true"
        app: cvat-proxy
    spec:
      containers:
        - image: nginx:1.18.0-alpine  #openvino/cvat_ui
          #imagePullPolicy: Never
          name: cvat-proxy
          volumeMounts:
          - name: mysite-configs
            mountPath: /etc/nginx/conf.d
      volumes:
          - name: mysite-configs
            configMap:
              name: mysite-config
---
apiVersion: v1
kind: Service
metadata:
  name: cvat-service
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    nodePort: 30007  
 
  selector:
    app: cvat-proxy

