apiVersion: v1
kind: ConfigMap
metadata:
  name: mysite-config
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;                
      server_name  _;
      location / {
              #  try_files $uri $uri/ /index.html;
              #  add_header  Cache-Control: "no-cache, no-store, must-revalidate";
              #   add_header  Pragma: "no-cache";
              #        add_header  Expires: 0;
                proxy_pass "http://test:80/";
                client_max_body_size 200000M;
                add_header  Cache-Control: 'Access-Control-Allow-Origin *';
                add_header Access-Control-Max-Age 3600;
                add_header Access-Control-Expose-Headers Content-Length;
                add_header Access-Control-Allow-Headers Range;
                add_header Access-Control-Expose-Headers "Origin";
 
       }

       location /api/ {
                proxy_pass "http://cvatsvc:8080";
                client_max_body_size 200000M;
                add_header  Cache-Control: 'Access-Control-Allow-Origin *';
                add_header Access-Control-Max-Age 3600;
                add_header Access-Control-Expose-Headers Content-Length;
                add_header Access-Control-Expose-Headers "Origin";
                add_header Access-Control-Allow-Headers Range;
       }
       #  location /analytics/ {
       #  proxy_pass http://kibana:5601/;
       # } 
 
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
    traefik.enable: "true"
    traefik.http.routers.cvat-ui.entrypoints: web
    traefik.http.routers.cvat-ui.rule: Host(`localhost`)
    traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-proxy
  name: cvat-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-proxy
  template:
    metadata:
      annotations:
        traefik.enable: "true"
        traefik.http.routers.cvat-ui.entrypoints: web
        traefik.http.routers.cvat-ui.rule: Host(`localhost`)
        traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
      labels:
        io.kompose.network/cvat: "true"
        app: cvat-proxy
    spec:
      containers:
        - image: nginx:1.18.0-alpine  #openvino/cvat_ui
          #imagePullPolicy: Never
          name: cvat-proxy
          volumeMounts:
          - name: mysite-config
            mountPath: /etc/nginx/conf.d
      volumes:
          - name: mysite-config
            configMap:
              name: mysite-config
---
apiVersion: v1
kind: Service
metadata:
  name: cvat-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30007  
 
  selector:
    app: cvat-proxy

