apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
    traefik.enable: "true"
    traefik.http.routers.cvat-ui.entrypoints: web
    traefik.http.routers.cvat-ui.rule: Host(`localhost`)
    traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-proxy
  name: cvat-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
        traefik.enable: "true"
        traefik.http.routers.cvat-ui.entrypoints: web
        traefik.http.routers.cvat-ui.rule: Host(`localhost`)
        traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
      creationTimestamp: null
      labels:
        io.kompose.network/cvat: "true"
        io.kompose.service: cvat-ui
    spec:
      containers:
        - image: nginx:1.18.0-alpine  #openvino/cvat_ui
          #imagePullPolicy: Never
          name: cvat-ui
