apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvat-data
  namespace: cvat-prod
spec:
  storageClassName: cvat-prod
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
   - ReadOnlyMany
   - ReadWriteMany
  # hostPath:
  #   path: "/tmp/cvat-data"
  volumeMode: Filesystem
  nfs:
    server: 10.40.41.57
    path: /home/apexon/nfs-storage/cvat-data
    readOnly: no
  mountOptions:
    - hard
    - nfsvers=4.1
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: cvat-data
      namespace: cvat-prod
