apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-keys
  name: cvat-keys
  namespace: cvat-prod
spec:
  storageClassName: cvat-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
