apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
  namespace: cvat-prod
spec:
  storageClassName: cvat-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
status: {}
