apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-setup
  namespace: cvat-prod
spec:
  storageClassName: cvat-prod
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
   - ReadOnlyMany
   - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: 10.40.41.57
    path: /home/apexon/nfs-storage/kibana-setup
    readOnly: no
  mountOptions:
    - hard
    - nfsvers=4.1
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: cvat-kibana-setup-claim0
      namespace: cvat-prod