apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
  namespace: cvat-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/cvat: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - image: 10.40.41.59:5000/apexon-cvat_kibana  #cvat_kibana
          #imagePullPolicy: Never
          name: cvat-kibana
          env:
            - name: NFS_SERVER
              value: 10.40.41.57
            - name: NFS_PATH
              value: /home/apexon/nfs-storage
          resources: {}
      restartPolicy: Always
status: {}
