apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-redis
  name: cvat-redis
  #namespace: cvat-prod
spec:
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: cvat-redis
#   type: LoadBalancer
status:
  loadBalancer: {}
