apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-kibana-setup
  name: cvat-kibana-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-kibana-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/cvat: "true"
        io.kompose.service: cvat-kibana-setup
    spec:
      containers:
        - command:
            - bash
            - wait-for-it.sh
            - elasticsearch:9200
            - -t
            - "0"
            - --
            - /bin/bash
            - wait-for-it.sh
            #- kibana:5601
            - 10.107.131.198:5601
            - -t
            - "0"
            - --
            - python3
            - kibana/setup.py
            - kibana/export.json
          env:
            - name: no_proxy
              value: elasticsearch,kibana,
            - name: NFS_SERVER
              value: 10.40.41.57
            - name: NFS_PATH
              value: /home/apexon/nfs-storage
          image: 10.40.41.59:5000/apexon-cvat_server   #openvino/cvat_server
          #imagePullPolicy: Never
          name: cvat-kibana-setup
          resources: {}
          volumeMounts:
            - mountPath: /home/django/kibana
              name: cvat-kibana-setup-claim0
              readOnly: true
          workingDir: /home/django
      restartPolicy: Always
      volumes:
        - name: cvat-kibana-setup-claim0
          persistentVolumeClaim:
            claimName: cvat-kibana-setup-claim0
            readOnly: true
status: {}
