apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvat-data
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
   - ReadOnlyMany
   - ReadWriteMany
  hostPath:
    path: "/mnt/cvat-data/"
  #  volumeMode: Filesystem
  #nfs:
  #server: 10.40.41.57
  # path: /home/apexon/nfs-storage/cvat-data
  # readOnly: no
  #mountOptions:
  # - hard
  # - nfsvers=4.1
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: cvat-data
      namespace: default
