apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-cvat-redis-master-0
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  # hostPath:
  #   path: "/mnt/redis-data-cvat-redis-master-0"
  volumeMode: Filesystem
  nfs:
  server: 10.40.41.57
  path: /home/apexon/redis-data-cvat-redis-master-0"
  readOnly: no
  mountOptions:
  - hard
  - nfsvers=4.1
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: redis-data-cvat-redis-master-0
      namespace: default
