apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-cvat-redis-replicas-0
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/redis-data-cvat-redis-replicas-0"
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: redis-data-cvat-redis-replicas-0
      namespace: default

